name: Compilation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest  ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Install compiler
        id: install_cc
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: gcc-latest
        
      - name: Use compiler
        # env:
        #     CC: ${{ steps.install_cc.outputs.cc }}
        run: |
          echo "Generate output folder"
          mkdir output
          ls
          echo "Compile source code"
          gcc -v -Wall -Wpedantic -Wextra src/*.c -o "output/petits_chevaux"

      - name: Export binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.os}}_binary
          path: output/petits_chevaux
